### ISSUE TITLE
Berichten

### ISSUE THREAD

**Issue by Wanny16** [sprksoft/smpp#10]
Beste,

Wanneer je een bericht ontvangt, kan je niet naar beneden scrollen. Dit is niet handig, omdat je soms een deel van de tekst niet kan lezen, en ook omdat je dan geen bijlages kan openen.

Mvg, gebruiker
![Schermafbeelding 2024-09-20 154455](https://github.com/user-attachments/assets/369c1fa5-4b8c-4c0c-b768-19badf88cb89)

**Comment by NightFlavor** [comment]
Dit is gepatched
