### ISSUE TITLE
OPEN API KEY IN DELIJN.js (with lars2800)

### ISSUE THREAD

**Issue by raspipy** [sprksoft/smpp#8]
Gast fix da lmao.
![image](https://github.com/user-attachments/assets/5054ee09-bdec-489a-a991-62057e7ad098)

**Comment by Xgames123** [comment]
wat verwacht jij wat wij doen
die key moet visible zijn voor de client en das een free key

**Comment by JJorne-JDEVJ** [comment]
![image](https://github.com/user-attachments/assets/d2e27e4c-31d3-4f7c-9ea6-db22a203dee8)
tada! owner van deze extentie (nightflavour) heeft 4 maand geleden gezegd dat het niet zo erg is
